### ISSUE TITLE
Create Slides and Report

### ISSUE THREAD

**Issue by ClementineAccount** [ClementineAccount/csd3156-TeamProject-group7#14]
# Summary
Create the slides in order to demonstrate what is our application and the mobile features that are included.

# Task List
- [x] Create slides on Google Slides 
- [ ] Create mockup of the application
- [ ] Demonstrate in each screen what is the mobile feature that is used
- [ ] Show off application live demo as video
- [ ] Conclusion and Summary

**Comment by ClementineAccount** [comment]
The link to this project's report can be found here: (https://docs.google.com/document/d/1Pa2NDl_YiSsUN_LS5waNF5DBgIZ41OX_DScyN7MaiV4/edit#heading=h.1dfqzzjhht5z)
