### ISSUE TITLE
Update Shop Screen to include Credit and Shape as well as Unlock System

### ISSUE THREAD

**Issue by ClementineAccount** [ClementineAccount/csd3156-TeamProject-group7#17]
# Summary
After discussion with @VentusFlame, we updated the shop screen to take in account a feature.
We want to have the Credits and Shape currency be separate for gameplay progression reasons, similar to the picture below.
![image](https://github.com/ClementineAccount/csd3156-TeamProject-group7/assets/26779639/879999c2-b35c-4342-962f-3688ff4b5eed). 

Currently, the shop activity looks like this as of this issue date:
![image](https://github.com/ClementineAccount/csd3156-TeamProject-group7/assets/26779639/9f5257ae-f0c4-4c19-a158-50aaf543aeb6)

Additionally, we are also scoping down the requirements so that the database only is concerned with local storage for now as the minimum viable product.

Note: We do not need to match the color. Only the layout and functionality

# Task List
(I need to fill this up more)
- [ ] Add 'Upgrade' Screen
- [x] Match UI to match specifications better
- [ ] Add 'Credits' option
- [ ] Update Database to incorporate the two variables
- [x] Add 'How to Play' Text
