### ISSUE TITLE
Add a Recycler View list of Current GPS coordinates to the MapActivity

### ISSUE THREAD

**Issue by ClementineAccount** [ClementineAccount/csd3156-TeamProject-group7#20]
# Summary
We should add a recycler view in order to preview the current farms that exist in the world. When the button is clicked, the map should automatically move the camera to show it. The farm radius circles should also be labelled to match the farm.

For testing, we can use mock data from a list that is generated. The task to integrate it with the database can be considered a separate issue page feature. Currently the GPS lists looks like this:

![Screenshot_20240223_134716_HelloAR_Kotlin](https://github.com/ClementineAccount/csd3156-TeamProject-group7/assets/26779639/7a7f7cb5-8b40-4928-bd6d-61b137325d1d)

# Example 
A rough mockup made in less than a few minutes in Figma. Don't worry about the aesthetic for now just follow the functionality.
![image](https://github.com/ClementineAccount/csd3156-TeamProject-group7/assets/26779639/6704dc1e-0f33-4241-be68-05cb3f5484bc)

# Task List
- [x] Create test data of at least 5 GPS coordinate points, preferably in Singapore. (Done by Tap)
- [x] RecylclerView list shows the 5 GPS points
- [ ] ~~When the recylerview list item is clicked, the camera automatically zoom and move to the GPS point selected.~~ (N/A. Turned to its own issue)
- [x] When new GPS point is added, the list is refreshed also in the recylerview.
