### ISSUE TITLE
Use Geospatial API to restore Farm Anchor data

### ISSUE THREAD

**Issue by ClementineAccount** [ClementineAccount/csd3156-TeamProject-group7#25]
# Summary
For simplification of the task, we can use [Google's ARCore Geospatial Anchor](https://developers.google.com/ar/develop/geospatial) to restore an object based off horizontal and vertical coordinates.

> You can place a Geospatial anchor almost anywhere in the world at a given latitude, longitude and altitude without needing to manually map the space. 

This would allow easier testing based off our use case, and allow the GPS data that is retrieved and stored to be used to have persistent farms viewable in AR Activity across sessions. There may be a need to amend the MapActivity to display Altitude as well as an additional data in the RecylerView for that activity. 

# Task List
- [x] Ensure Geospatial API Key is working with the project
- [ ] Store the Geospatial data into local database using Farm Item's DAO
- [ ] Retrieve Geospatial data from local phone database to place the objects into the world in the AR Activity.
