### ISSUE TITLE
Visual Effect when Item is Pressed

### ISSUE THREAD

**Issue by ClementineAccount** [ClementineAccount/csd3156-TeamProject-group7#30]
# Summary

Currently there is no indicator or feedback when an item is pressed in the Activity. The functionality to detect the press has been implemented in #29 . It would be nice to have a bit of tweening animation and a number indicator (can be just UI screen rather than worldspace) when item is pressed

Similar to the example.

![image](https://github.com/ClementineAccount/csd3156-TeamProject-group7/assets/26779639/24114888-46f5-46e1-9162-200011c334fd)

Figma Example of the minimum version, where a popup would show everytime you tap it (not toast notification). This can be done in the Screenspace for the activity as our first iteration (not sure if will have time to do the version in World Space)
![image](https://github.com/ClementineAccount/csd3156-TeamProject-group7/assets/26779639/3b0ea567-9c87-4028-a80c-bf00ea341e27)

The current code for interacting with a tapping that was done. This is found in HelloArRenderer.kt as off the latest commit in main branch
![image](https://github.com/ClementineAccount/csd3156-TeamProject-group7/assets/26779639/5f61be16-71f9-4015-bcb6-aaefa1e27fe7)

# Task List
- [ ] Implement visual effect when item is pressed -> Tweening
- [ ] Implement visual effect when item is pressed -> Number Counter go Up
- [ ] Click Sound Effect when item is pressed
