### ISSUE TITLE
Create Report

### ISSUE THREAD

**Issue by ClementineAccount** [ClementineAccount/csd3156-TeamProject-group7#32]
# Summary
Need to do report for the Team Project. The following screenshots are from the rubrics.
![image](https://github.com/ClementineAccount/csd3156-TeamProject-group7/assets/26779639/49e9e437-bad8-4070-8e30-580828277b0d)

![image](https://github.com/ClementineAccount/csd3156-TeamProject-group7/assets/26779639/3d818a4f-ee20-4dad-baef-d55489f62fd3)

Use GitHub Issues board as a reference to document who worked on what activity.

# Task List
- [x] Create skeleton of the report on Google Docs and add it as comment here as editable link
- [ ] Fill up the requirements of the report according to the rubrics
- [ ] Describe each mobile feature used for the following screens as well as well as who worked on what:
- [ ] Map Activity
- [ ] Shop Activity
- [ ] AR Activity 
- [x] Include reference to [Database Documentation](https://github.com/ClementineAccount/csd3156-TeamProject-group7/issues/24)
- [ ] Include attribution for all assets used such as the (sound effect)[https://github.com/ClementineAccount/csd3156-TeamProject-group7/issues/15]
