### ISSUE TITLE
Add RESTful API for updating based off Weather in ShopActivity

### ISSUE THREAD

**Issue by ClementineAccount** [ClementineAccount/csd3156-TeamProject-group7#34]
# Summary
We should have an additional feature that allow the price to be affected by a multiplier based off the current weather. We can get the weather data using a free weather api like [Weather AP](https://www.weatherapi.com/) or [Open Weather Map](https://openweathermap.org/api) (whichever easiest). 

The example of how weather may look might look something like this but nicer and maybe got icon of the weather if can.
![image](https://github.com/ClementineAccount/csd3156-TeamProject-group7/assets/26779639/cb3e9dd0-a944-4824-ad65-dcdfe4289ca7)

# Task List
- [x] Get Weather Data from a Restful API
- [x] Display the weather on ShopActivity
- [x] Have the weather variable affect the price
