### ISSUE TITLE
Add the UI to AR Activity

### ISSUE THREAD

**Issue by ClementineAccount** [ClementineAccount/csd3156-TeamProject-group7#37]
# Summary
Currently our AR Activity screen has this interface

![Screenshot_20240227_120324_HelloAR_Kotlin](https://github.com/ClementineAccount/csd3156-TeamProject-group7/assets/26779639/bc9da8ca-5b30-4cdd-ad2a-d018c37a50e8)

But our AR Activity should resemble this screen more with interface to navigate:
![image](https://github.com/ClementineAccount/csd3156-TeamProject-group7/assets/26779639/abedff1f-cdb5-4e04-b796-3788a79a5f8c)

# Task List
- [ ] Add Shop Button
- [ ] Add Map Button
- [ ] Display the currently selected Item (Must have some interface for it) -> Just worry front end for this one we will swap in the logic later
