### ISSUE TITLE
Add the Distance Radius Check for the Maps Activity

### ISSUE THREAD

**Issue by ClementineAccount** [ClementineAccount/csd3156-TeamProject-group7#4]
# Summary
We wish to be able to detect where the user is relative to points of interest on the map. This feature will be used later to allow a user to build 'farms', which are defined as circles on the map. 

This issue describes the backend aspect of the feature, which is to simply detect whether the GPS reading of the user is near some hardcoded test values. The following image shows a rough mockup sketch of the idea. The rendering and visual feedback of whether the user is within the circle will be defined in a separate Issues page. This will be done inside the [MapsActivity](https://github.com/ClementineAccount/csd3156-TeamProject-group7/blob/main/app/src/main/java/com/csd3156/team7/MapsActivity.kt) file.

Rendering the visual display of the points of interest is described by #5

![image](https://github.com/ClementineAccount/csd3156-TeamProject-group7/assets/26779639/14fbdc99-7709-4ca5-adfb-7ca8f799070b)

# Task List 
- [ ] Create a few hardcoded test point of interests. These are positions with a configurable radius
- [ ] Set the GPS position to be outside the circle -> should not print anything
- [ ] Set the GPS position to be inside the circle -> should print 'Inside Farm [N]' where N is the farm's ID
