### ISSUE TITLE
Redesign AR and Map Concept

### ISSUE THREAD

**Issue by ClementineAccount** [ClementineAccount/csd3156-TeamProject-group7#41]
# Summary
When doing more research and trying to complete the features for the [Geospaitial Anchor using ARCore](https://developers.google.com/ar/develop/geospatial), we came across some unexpected blockers. The major blocker that has halt our progress was that the Geospatial Anchor included in ARCore is simply not accurate enough 'out of the box' for our activity scope. 

This was seen in the fact that the farm items that were created using the [Geospaitial Anchor function create from hitPose](https://developers.google.com/ar/develop/java/geospatial/anchors) 
`var pose : GeospatialPose = activity.earth.getGeospatialPose(hitPose)`

At first implementation, I had assumed that I had done something wrong. What would happen is that anchors created using Geospaitial would fly around erratically. (The unlit cube above the one on the plane is the one created using GPS, with the altitude set to be that of the phone). I assume it has something to do with inconsistent Tracking Planes. 

![Screenshot_20240227_123527_HelloAR_Kotlin](https://github.com/ClementineAccount/csd3156-TeamProject-group7/assets/26779639/652ae57f-2433-49b1-86fb-6d1a4002ae6f)
![Screenshot_20240227_123609_HelloAR_Kotlin](https://github.com/ClementineAccount/csd3156-TeamProject-group7/assets/26779639/ca1c460e-1667-469f-9272-f2f4e6d74b67)

I do not know why [Ballon Tap Unity](https://github.com/googlecreativelab/balloon-pop) was able to place the GPS anchors without issues (seemingly from the screenshot and video) but the [Geospaitial Quickstart](https://developers.google.com/ar/develop/java/geospatial/quickstart) had similar issues with the default app. All the working examples like [Pocket Garden](https://github.com/buck-co/PocketGarden/tree/master) are done in Unity and use a mixture of Cloud Anchor and Geospaitial.

There were two solutions considered to solve the problem:
- Use ['Cloud Anchor'](https://developers.google.com/ar/develop/cloud-anchors) to store the data and location data to retrieve it
- Rework our design to consider only GPS location without worrying about tracking accuracy or depth placement

Since we were running short of time and we didn't want to risk this issue being a huge blocker for our app, we decided to change the scope of our project a bit. 

We decided that instead of keeping track of planes and hit placement, we could simplify our concept so that the user is able to create a farm radius at a GPS location, and that farm indicator would exist in a space that does not need to consider depth test. When the user is within the radius of that GPS Location as indicated, they would receive the farm item. (This might need to be a Service)

Additionally, when they are within the location, a mini game can be played so that they can collect the Items by tapping on them as they randomly spawn around.

This issue is focused on the AR Side of things

![image](https://github.com/ClementineAccount/csd3156-TeamProject-group7/assets/26779639/03269382-fb9b-46de-b6eb-542ae819e61a)

Use WorldSpace

Need to do the actual AR Stuff.

I want to spawn the cubes on the plane at random spots on that plane (relative to the camera)

One approach I can think of is the following:

1) Make sure the plane is created
2) Have the player 'tap' to create the collectable anchor item
3) Have those anchor items offset relative to the tap spot by a certain radius and random
4) Allow detection of tapping near it again to interact with it

It shouldn't be too bad. We can implement Step 2 to Step 4 first

# Task List
- [ ] ~~Add debug button for creating a farm that updates in database~~
- [ ] ~~Display a huge icon indicator that shows the center~~
- [x] Spawn Item in front of player camera at random
- [x] Allow tapping item to get some result
- [ ] ~~When item is tapped, adds that item to database~~
