### ISSUE TITLE
Add 'Farm Update' Service

### ISSUE THREAD

**Issue by ClementineAccount** [ClementineAccount/csd3156-TeamProject-group7#43]
# Summary
Using [Android Service](https://developer.android.com/develop/background-work/services), we can detect at all times when the app is opened whether we are within a Farm Radius of the matching item. For this issue, it simply will handle the Service and will not do the distance radius check against a database until the completion of #40. This will allow the service to run in the background.

# Task List
- [x] Create a service that increments a local variable whenever the app is opened
- [ ] ~~Create unit tests to check that service is running properly (finally some TDD in this project this AR stuff have been tripping me up)~~
- [x] Have the service read this local variable from a database upon starting
- [x] After the first two is completed, have the service must update the database. The Inventory Screen will also be updated to show it, and later on the UI elements for all the other screens.
- [ ] Have the service add the item for different types of farms.
- [x] Ensure that Service is non-blocking when interacting with the database
