### ISSUE TITLE
Allow 'Farm Update' Service to take in account GPS location

### ISSUE THREAD

**Issue by ClementineAccount** [ClementineAccount/csd3156-TeamProject-group7#44]
# Summary
This is a combination of the following two issues which must be completed first:
#40 
#43 

This issue describes implementing the Service to take in account whether the player is within a GPS farm location that matches the item type. This is so that the user is only able to receive the farm item when within that location.

# Task List
- [ ] Create unit test
- [ ] When the player is within a farm area, update the database with the value
- [ ] When the player leaves the farm area, do not increment the value
- [ ] Have a notification indicating whether the player is within or outside the areas.
