### ISSUE TITLE
Create shader and texture to allow shapes to be colored at runtime + Add additional shape

### ISSUE THREAD

**Issue by ClementineAccount** [ClementineAccount/csd3156-TeamProject-group7#45]
# Summary
Currently the green cube uses a green texture. Instead it should use a white texture and use a shader to apply an additive color to it relative to what is stored in the database.

EDIT: Also add the shape for the other two shapes

# Task List
- [ ] Replace green texture with a white texture -> @VentusFlame 
- [x] Convert Int Hex Color that is stored Database to RGB floats through a function -> @VentusFlame 
- [ ] Create a shader that allows the color data to be a variable read from database (RGB values) -> @ClementineAccount 
- [ ] Add additional shape model: Pyramid
- [ ] Add additional shape model: Sphere
