### ISSUE TITLE
Select Farm Type through Shop Activity Screen

### ISSUE THREAD

**Issue by ClementineAccount** [ClementineAccount/csd3156-TeamProject-group7#47]
# Summary 
Allow the user to select the farm type from this screen so that they can choose the farm to build inside the AR Screen.
![Untitled](https://github.com/ClementineAccount/csd3156-TeamProject-group7/assets/26779639/6ca0a84f-e9a4-4c02-8f18-8d8a5290d24a)

So that it can be shown when the user try to build inside AR Activity #37 
![308032696-abedff1f-cdb5-4e04-b796-3788a79a5f8c](https://github.com/ClementineAccount/csd3156-TeamProject-group7/assets/26779639/d2182004-247c-4f5a-92ea-ba2d27fc692a)

# Task List
- [x] Have a static variable that is accessible globally indicating the currently selected farm in ShopActivity
- [x] Allow selecting the farm from the Shop Activity screen
- [x] Have the first farm be selected as default when starting the app
