### ISSUE TITLE
Music Player Service

### ISSUE THREAD

**Issue by ClementineAccount** [ClementineAccount/csd3156-TeamProject-group7#50]
# Summary
It would be a good way to showcase the mobile feature of using a Service to change music depending on the currently running Activity. This would also improve the user experience. For prototyping, we can use placeholder music for activities that will change as the user navigates to different activities. The music should be able to also be looping and it should not be playing if the app is not active.

An example of a music media player can be found in HelloArRenderer.kt
![image](https://github.com/ClementineAccount/csd3156-TeamProject-group7/assets/26779639/892ca064-db92-4ebe-b9f4-f2cc175c8696)

An example of a [Service](https://developer.android.com/develop/background-work/services) can be found in FarmService file.

# Task List
- [x] Play a Shop Music during the Shop Menu
- [x] Play a Map Music during the Map Menu
- [x] Play an AR Music during the AR Screen -> This one optional if cannot do just pull request
- [x] Music changes when the screen changes
