### ISSUE TITLE
Intergrate UI Elements to Item Collectable in AR Minigame

### ISSUE THREAD

**Issue by ClementineAccount** [ClementineAccount/csd3156-TeamProject-group7#53]
# Summary

Integrate #37 together with #52 so that the visual effects are indicated when tapping the item. Additionally, add some health bar condition to the item when tapping. This is probably more fun. Also some sound effects when the thing is tapped

# Task List
- [ ] Visual Indicator on thing when tapped
- [ ] Item can be tapped many times before it disappears
- [ ] Sound Effects when thing is tapped.
