### ISSUE TITLE
Figma Mockup

### ISSUE THREAD

**Issue by ClementineAccount** [ClementineAccount/csd3156-TeamProject-group7#7]
# Summary
There should be a simple Figma Mockup, which showcases how the different Activities and features of the app interact with each other. This makes it clearer to understand what the contributions are, as well as the scope of the product. This mockup can also be used for the report and presentation 

# Task List 
- [x] Mockup Starting Screen
- [x] Mockup AR Screen
- [ ] Mockup Map Screen
- [x] Mockup Inventory/Shop Screen
- [x] Mockup NFC Screen
