### ISSUE TITLE
Create the GitHub Issues for some leftover tasks discussed in the meeting (for Week 4)

### ISSUE THREAD

**Issue by ClementineAccount** [ClementineAccount/csd3156-TeamProject-group7#8]
# Summary
During some meetings in the past, I had discussed the task allocation for some members. I need to create some of the issues retroactively so that people can be properly credited for the work they had previously done, as well as a form of reference and documentation for future issues. There are also some upcoming features that still need to be made.

# Task List
Issues I still need to create
- [ ] NFC Example Activity
- [ ] Creating the starting files (this repo + api stuff)
- [ ] Inventory Screen Front End
- [ ] Inventory Stuff Back End (Database)
- [x] ~~Multi-threading for Idle Mechanic~~ Don't do for Week 4
- [ ] AR Features with placing/clicking the farms
- [ ] NFC Implementation with Shop
- [x] ~~Database with Cloud (Firebase and/or AWS)~~ Don't do for Week 4
